# Generated by Django 2.0.4 on 2018-04-25 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_liba', '0002_auto_20180425_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_dearth',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='author',
            name='years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='book_id',
            field=models.ManyToManyField(related_name='author', to='my_liba.Book'),
        ),
    ]
