# Generated by Django 2.0.4 on 2018-04-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
