# Generated by Django 2.0.4 on 2018-04-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0002_auto_20180422_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
    ]
