# Generated by Django 2.0.4 on 2018-04-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0003_auto_20180422_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
