# Generated by Django 2.0.4 on 2018-04-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0004_mechanic_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='number',
        ),
        migrations.AddField(
            model_name='month',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
