# Generated by Django 2.0.4 on 2018-04-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0005_auto_20180422_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='week',
            field=models.CharField(default='', max_length=250),
        ),
    ]
