# Generated by Django 2.0.4 on 2018-04-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0007_timetable_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='number',
        ),
        migrations.RemoveField(
            model_name='month',
            name='week',
        ),
        migrations.AddField(
            model_name='month',
            name='days_in_month',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='free_days',
            field=models.CharField(blank=True, default='', help_text='Enter the day that is free of work. If there are several days, please enter in one line with comma-separate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='public_holidays',
            field=models.CharField(blank=True, default='', help_text='Enter the the days of public holidays in this month. If there are several holidays, please enter in one line with comma-separate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='week_days',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[('January', 1), ('February', 2), ('March', 3), ('April', 4), ('May', 5), ('June', 6), ('Jule', 7), ('August', 8), ('September', 9), ('October', 10), ('November', 11), ('December', 12)], default='', max_length=20),
        ),
    ]
