# Generated by Django 2.0.4 on 2018-04-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0008_auto_20180430_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='working_days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='timetable_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='days_in_month',
            field=models.IntegerField(blank=True, default=31, null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'Jule'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default='', max_length=20),
        ),
    ]
