# Generated by Django 2.0.4 on 2018-05-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0013_auto_20180430_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='start_with',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'Jule'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='', max_length=200),
        ),
    ]
