# Generated by Django 2.0.4 on 2018-05-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0014_auto_20180503_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='mechanic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='TimeTable.Mechanic'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='month_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_name', to='TimeTable.Month'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_with',
            field=models.CharField(blank=True, default='', help_text="Enter 3 first days in the timetable. The correct format is:  'd,d,d', 0 - is free day; 23 - is first shift; 7 - is second shift; 15 - is third shift ", max_length=20, null=True),
        ),
    ]
