# Generated by Django 2.0.4 on 2018-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0015_auto_20180506_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
