# Generated by Django 2.0.4 on 2018-05-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0016_month_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanic',
            options={'permissions': (('can_add_mechanic', 'Create a mechanic'),)},
        ),
        migrations.AlterField(
            model_name='month',
            name='days_in_month',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timetable',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
