# Generated by Django 2.0.4 on 2018-05-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0018_auto_20180507_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='image',
            field=models.ImageField(default='', upload_to='media/images', verbose_name='main_image'),
        ),
    ]
