# Generated by Django 2.0.4 on 2018-05-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0019_mechanic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/images'),
        ),
    ]
